apiVersion: v1
kind: Service
metadata:
  name: {{ include "preview_service.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "preview_service.labels" . | indent 4 }}
spec:
  selector:
    app: speckle-preview-service
    project: speckle-server
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.preview_service.port }}
      targetPort: {{ .Values.preview_service.port }}
---
# Original metrics service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "preview_service.name" . }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
{{ include "preview_service.labels" . | indent 4 }}
spec:
  selector:
    app: speckle-preview-service
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: {{ .Values.preview_service.monitoring.metricsPort }}
      targetPort: metrics